### ISSUE TITLE
No conflict if two PR change two different subfolders

### ISSUE THREAD

**Issue by SpaceIm** [ericLemanissier/conan-center-conflicting-prs#8]
The bot shouldn't report a conflict if two PR make modifications in different subfolders like 2.x.x and 3.x.x.

sol2 recipe for example:
https://github.com/conan-io/conan-center-index/pull/3933 modifies subfolder 2.x.x
https://github.com/conan-io/conan-center-index/pull/3472 modifies subfolder 3.x.x

**Comment by ericLemanissier** [comment]
yes, I'll improve this tonight, thanks !
