### ISSUE TITLE
"pull requests modify several recipes, so they were ignored" is outdated

### ISSUE THREAD

**Issue by Croydon** [ericLemanissier/conan-center-conflicting-prs#9]
CCI allows now to modify several versioned folders of a single package

**Comment by ericLemanissier** [comment]
Thanks !
I think this is fixed with https://github.com/ericLemanissier/conan-center-conflicting-prs/commit/e2dafce51d7a7723b369ca21c61a544bb0c9d643 + https://github.com/ericLemanissier/conan-center-conflicting-prs/commit/e2859871cf9a7980ffdb9e0bd09fafff80ade5ef
